# Generated by Django 5.2.7 on 2025-11-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('mat_id', models.AutoField(db_column='matId', primary_key=True, serialize=False)),
                ('mat_cadastrado_em', models.DateTimeField(db_column='matCadastradoEm')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'db_table': 'matricula',
                'managed': False,
            },
        ),
    ]
