# Generated by Django 5.2.7 on 2025-11-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('tre_id', models.AutoField(db_column='treId', primary_key=True, serialize=False)),
                ('tre_nome', models.CharField(db_column='treNome', max_length=160)),
                ('tre_descricao', models.TextField(blank=True, db_column='treDescricao', null=True)),
                ('tre_cadastrado_em', models.DateTimeField(db_column='treCadastradoEm')),
            ],
            options={
                'verbose_name': 'Treinamento',
                'verbose_name_plural': 'Treinamentos',
                'db_table': 'treinamento',
                'ordering': ['tre_nome'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('tru_id', models.AutoField(db_column='truId', primary_key=True, serialize=False)),
                ('tru_nome', models.CharField(db_column='truNome', max_length=160)),
                ('tru_data_inicio', models.DateTimeField(db_column='truDataInicio')),
                ('tru_data_conclusao', models.DateTimeField(blank=True, db_column='truDataConclusao', null=True)),
                ('tru_link_acesso', models.CharField(blank=True, db_column='truLinkAcesso', max_length=255, null=True)),
                ('tru_cadastrado_em', models.DateTimeField(db_column='truCadastradoEm')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'db_table': 'turma',
                'ordering': ['-tru_data_inicio'],
                'managed': False,
            },
        ),
    ]
