# Generated by Django 5.2.7 on 2025-11-02 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('pef_id', models.AutoField(db_column='pefId', primary_key=True, serialize=False)),
                ('pef_nome', models.CharField(db_column='pefNome', max_length=100)),
                ('pef_cadastrado_em', models.DateTimeField(auto_now_add=True, db_column='pefCadastradoEm')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'db_table': 'perfil',
                'ordering': ['pef_nome'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usu_id', models.AutoField(db_column='usuId', primary_key=True, serialize=False)),
                ('usu_nome', models.CharField(db_column='usuNome', max_length=200)),
                ('usu_email', models.EmailField(db_column='usuEmail', max_length=200, unique=True)),
                ('usu_telefone', models.CharField(blank=True, db_column='usuTelefone', max_length=32, null=True)),
                ('usu_cadastrado_em', models.DateTimeField(auto_now_add=True, db_column='usuCadastradoEm')),
                ('password', models.CharField(db_column='usuSenha', max_length=128)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('perfil', models.ForeignKey(db_column='usuPefId', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='accounts.perfil')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
                'ordering': ['usu_nome'],
                'managed': False,
            },
        ),
    ]
