# Generated by Django 5.2.7 on 2025-11-02 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'managed': False, 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
    ]
