# Generated by Django 5.2.7 on 2025-11-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('rec_id', models.AutoField(db_column='recId', primary_key=True, serialize=False)),
                ('rec_tipo', models.CharField(db_column='recTipo', max_length=10)),
                ('rec_acesso_previo', models.BooleanField(db_column='recAcessoPrevio')),
                ('rec_draft', models.BooleanField(db_column='recDraft')),
                ('rec_nome', models.CharField(db_column='recNome', max_length=160)),
                ('rec_descricao', models.TextField(blank=True, db_column='recDescricao', null=True)),
                ('rec_arquivo_path', models.CharField(db_column='recArquivoPath', max_length=512)),
                ('rec_cadastrado_em', models.DateTimeField(db_column='recCadastradoEm')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'db_table': 'recurso',
                'ordering': ['rec_nome'],
                'managed': False,
            },
        ),
    ]
